function Hd = FIR
%FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 21-Sep-2025 15:02:55

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 100e6;  % Sampling Frequency

N    = 50;       % Order
Fc   = 0.1e3;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
