function Hd = Lowpass
%LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 21-Sep-2025 20:07:04

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 20e3;  % Sampling Frequency

N    = 40;       % Order
Fc   = 1.5e3;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
